name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      # Optional: rebuild content from a vault checked out in the runner.
      - name: Optionally build content from a vault
        run: |
          if [ -n "$OBSIDIAN_VAULT_PATH" ]; then
            echo "Building content from $OBSIDIAN_VAULT_PATH"
            npm run build-content
          else
            echo "Skipping build-content; using committed data/content.json"
          fi
        env:
          OBSIDIAN_VAULT_PATH: ${{ secrets.OBSIDIAN_VAULT_PATH }}

      - name: Build static site (user/org site)
        if: endsWith(github.event.repository.name, '.github.io')
        run: npm run build

      - name: Build static site (project site)
        if: ${{ !endsWith(github.event.repository.name, '.github.io') }}
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ github.event.repository.name }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
